version: '2'

services:

  courses-ms:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - courses-db

  courses-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: courses-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
